# Site settings
title: zantetu.net
motto: 主にJavaをメインに調べたこととかの備忘録
email: aono.masashi@gmail.com
description: 主にJavaをメインに調べたこととかの備忘録
baseurl: ""
url: "http://zantesu.net"
twitter_username: __emon
github_username: aono-masashi

# Build settings
markdown: kramdown
